### ISSUE TITLE
support for volume  snapshot creation, deletion and restore

### ISSUE THREAD

**Issue by parthnavale** [linode/linode-blockstorage-csi-driver#107]
## General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [x] Have you explained your rationale for why this feature is needed? 
* [ ] Have you offered a proposed implementation/solution? 

----

### Steps to Reproduce the Problem

  1.
  1.
  1.

#### Additional Notes

----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

**Comment by shinebayar-g** [comment]
Without this implemented, is there any way to backup PVC volumes on LKE?

**Comment by mzimry** [comment]
hey, when is this feature planned to be released?

**Comment by acrogenesis** [comment]
Interesting I was trying to setup volume snapshots and didn't get it to work.

**Comment by nesv** [comment]
Hi everyone! Sorry for this ticket having sat here so long, unaddressed.

Unfortunately, the CSI driver is limited by what is exposed through the Linode API, which currently does not support snapshots for block storage volumes. Linode has "instance volumes" which are the hypervisor-local disks attached to a Linode instance, and those support snapshots, but there is currently no way to snapshot a block storage volume.

If you would like this feature to be added, the best course of action would be to submit a feature request to the [Linode Community Q&A](https://www.linode.com/community/questions/).
