### ISSUE TITLE
Reworking release process removed the generate manifests action commit from the process

### ISSUE THREAD

**Issue by srust** [linode/linode-blockstorage-csi-driver#137]
## General:

* [ ] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [ ] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [ ] Have you explained your rationale for why this feature is needed? 
* [ ] Have you offered a proposed implementation/solution? 

----

### Expected Behavior

Previous release processes generated the release deploy yaml from the base yaml and created a commit for the release-specific yaml.

This generate manifests action was removed and no longer does this.

The release specific yaml is uploaded as an asset, but is not checked in.

As of today, we have a new release, but not a new release specific deployment yaml in the repo.

Removed:
```
--- a/.github/workflows/generate-manifest.yml
+++ /dev/null
@@ -1,21 +0,0 @@
-name: Release manifests
-on:
-  release:
-    types: [ published ]
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # pin@master
-      - name: Build manifest
-        run: "./hack/release-yaml.sh ${{ github.event.release.tag_name }}"
-      - name: Commit files
-        run: |
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add -- pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver*\.yaml
-          git commit -m "Update manifests"
-      - name: Push changes
-        uses: ad-m/github-push-action@65392840bda2e774394d5cd38ca33e5918aec2d3 # pin@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
```

```
releases srust$ ls
linode-blockstorage-csi-driver-v0.0.1.yaml  linode-blockstorage-csi-driver-v0.2.0.yaml
linode-blockstorage-csi-driver-v0.0.2.yaml  linode-blockstorage-csi-driver-v0.2.1.yaml
linode-blockstorage-csi-driver-v0.0.3.yaml  linode-blockstorage-csi-driver-v0.3.0.yaml
linode-blockstorage-csi-driver-v0.1.0.yaml  linode-blockstorage-csi-driver-v0.4.0.yaml
linode-blockstorage-csi-driver-v0.1.2.yaml  linode-blockstorage-csi-driver-v0.4.1.yaml
linode-blockstorage-csi-driver-v0.1.3.yaml  linode-blockstorage-csi-driver-v0.5.0.yaml
linode-blockstorage-csi-driver-v0.1.4.yaml  linode-blockstorage-csi-driver-v0.5.1.yaml
linode-blockstorage-csi-driver-v0.1.5.yaml  linode-blockstorage-csi-driver-v0.5.2.yaml
linode-blockstorage-csi-driver-v0.1.6.yaml  linode-blockstorage-csi-driver-v0.5.3.yaml
linode-blockstorage-csi-driver-v0.1.7.yaml  linode-blockstorage-csi-driver.yaml
```

Previously as shown each release created a separate deployment.

### Steps to Reproduce the Problem

  1.
  1.
  1.

#### Additional Notes

Can this be re-instated please?
----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

cc @luthermonson

**Comment by luthermonson** [comment]
This was on purpose, we moved it to a release artifact, this job wasn't working any more

**Comment by nesv** [comment]
Given @luthermonson's comment, can this issue be closed out?
