### ISSUE TITLE
Unable to create Volumes without tags in v0.6

### ISSUE THREAD

**Issue by rammanoj** [linode/linode-blockstorage-csi-driver#146]
## General:

* [X] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [X] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [X] Have you explained your rationale for why this feature is needed? 
* [ ] Have you offered a proposed implementation/solution? 

----

## Bug Reporting
When a PVC claims for a PV. It's encountering an error in the `v0.6` release. PFA screenshot of the error:
![image](https://github.com/linode/linode-blockstorage-csi-driver/assets/21082378/ec380b55-cbd4-42ad-8407-565b1faa0c41)

Storage Class:
![image](https://github.com/linode/linode-blockstorage-csi-driver/assets/21082378/2c7d332a-6b3a-41d5-8cf4-e37ae355e92c)

PVC Yaml:
![image](https://github.com/linode/linode-blockstorage-csi-driver/assets/21082378/d8b382fb-5f06-4391-9892-d015f2edbea7)

No tags are being provided.

### Steps to Reproduce the Problem

  1. Create a Linode with 4/8 GB dedicated RAM
  2. Install minikube and start the Kubernetes server
  3. Install the helm chart with the latest version of the CSI driver
  4. Apply the above PVC file.

----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

**Comment by luthermonson** [comment]
https://github.com/linode/linode-blockstorage-csi-driver/pull/143

**Comment by luthermonson** [comment]
closing this issue, this will be fixed in v0.6.1

**Comment by rammanoj** [comment]
Thanks @luthermonson

**Comment by rammanoj** [comment]
@luthermonson when would 0.6.1 release?

**Comment by luthermonson** [comment]
as soon as #140 is merged
