### ISSUE TITLE
Some Kustomize features the project uses are deprecated

### ISSUE THREAD

**Issue by mhmxs** [linode/linode-blockstorage-csi-driver#157]
## General:

* [X] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [X] Have you checked to ensure there aren't other open or closed [Pull Requests](../../pulls) for the same bug/feature/question?

----

## Feature Requests:
* [ ] Have you explained your rationale for why this feature is needed? 
* [ ] Have you offered a proposed implementation/solution? 

----

## Bug Reporting

Some `Kustomize` features the project uses are deprecated.

```bash
make -C e2e test-manifest 
make: Entering directory '/home/rkovacs/src/github.com/linode/linode-blockstorage-csi-driver/e2e'
../hack/generate-yaml.sh canary > test/manifest/linode-blockstorage-csi-driver.yaml
# Warning: 'bases' is deprecated. Please use 'resources' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesJson6902' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
```

### Steps to Reproduce the Problem

  1. make -C e2e test-manifest 

### Environment Specifications

kustomize version - 5.1.1

#### Additional Notes

----

For general help or discussion, join the [Kubernetes Slack team](https://kubernetes.slack.com/messages/CD4B15LUR/details/) channel `#linode`. To sign up, use the [Kubernetes Slack inviter](http://slack.kubernetes.io/).

The [Linode Community](https://www.linode.com/community/questions/) is a great place to get additional support.

**Comment by komer3** [comment]
This was fixed in the following commit a while back: https://github.com/linode/linode-blockstorage-csi-driver/commit/f7705905557da66328d96114afc9ec1c9ebb1f9b

Closing this issue
