### ISSUE TITLE
Deploy CSI Driver - not working - 404 error

### ISSUE THREAD

**Issue by cs-91** [linode/linode-blockstorage-csi-driver#181]
The following command from the README is met with a 404 error:

`kubectl apply -f https://raw.githubusercontent.com/linode/linode-blockstorage-csi-driver/master/pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver.yaml`

error: unable to read URL "https://raw.githubusercontent.com/linode/linode-blockstorage-csi-driver/master/pkg/linode-bs/deploy/releases/linode-blockstorage-csi-driver-v0.5.3.yaml", server reported 404 Not Found, status code=404

**Comment by nesv** [comment]
Hi @cs-91 :wave: 

Sorry about this. The paths were changed, and the README was not updated accordingly. We will get that sorted out as soon as possible.
