### ISSUE TITLE
CSI Controller attempts to attach a volume that no longer exists

### ISSUE THREAD

**Issue by gbates101** [linode/linode-blockstorage-csi-driver#32]
## General:

* [x] Have you removed all sensitive information, including but not limited to access keys and passwords?
* [x] Have you checked to ensure there aren't other open or closed pull requests for the same bug/feature/question?

### Expected Behavior
When a PV is deleted from kubernetes and linode, do not attempt to reattach it.

### Actual Behavior
It seems that the CSI controller pod is attempting to attach volumes that no longer exist. For example, `pvc-137bd04e833a11e9` is not present when listing via `kubectl get pv` and `linode-cli volumes list`, but the CSI controller pod is repeatedly attempting to attach it.

### Steps to Reproduce the Problem
It's hard to say what reproduces the issue. My guess would be this is happening when I manually update a PV stuck deleting to remove the finalizer (which I have done at least 10 times so far).

### Environment Specifications
Kubernetes v.1.13.4 and docker 18.09.6, deployed via Rancher v2.2.0 using Linode driver.
CSI container is quay.io/k8scsi/csi-provisioner:v1.0.0

#### Screenshots, Code Blocks, and Logs
Snippet from `kubectl -n kube-system logs -f sts/csi-linode-controller -c csi-attacher`:
```
I0618 20:28:37.554372       1 controller.go:167] Started VA processing "csi-7f1e371f65e1da8bd52567982327aa1b6a0333e4c34e44848a3a47c635f4d562"
I0618 20:28:37.554391       1 csi_handler.go:91] CSIHandler: processing VA "csi-7f1e371f65e1da8bd52567982327aa1b6a0333e4c34e44848a3a47c635f4d562"
I0618 20:28:37.554420       1 csi_handler.go:118] Attaching "csi-7f1e371f65e1da8bd52567982327aa1b6a0333e4c34e44848a3a47c635f4d562"
I0618 20:28:37.554428       1 csi_handler.go:257] Starting attach operation for "csi-7f1e371f65e1da8bd52567982327aa1b6a0333e4c34e44848a3a47c635f4d562"
I0618 20:28:37.554443       1 csi_handler.go:380] Saving attach error to "csi-7f1e371f65e1da8bd52567982327aa1b6a0333e4c34e44848a3a47c635f4d562"
I0618 20:28:37.732259       1 request.go:530] Throttling request took 1.982750931s, request: PUT:https://10.43.0.1:443/apis/storage.k8s.io/v1beta1/volumeattachments/csi-ba3c9c854807ae7ad3b32f18609fa18db08cf2d91e259767ffdb1cf610943604
I0618 20:28:37.741604       1 csi_handler.go:390] Saved attach error to "csi-ba3c9c854807ae7ad3b32f18609fa18db08cf2d91e259767ffdb1cf610943604"
I0618 20:28:37.741649       1 csi_handler.go:101] Error processing "csi-ba3c9c854807ae7ad3b32f18609fa18db08cf2d91e259767ffdb1cf610943604": failed to attach: persistentvolume "pvc-137bd04e833a11e9" not found
```
This log message is repeated hundreds of times per minute, and from parsing logs I see there are at least 14 volumes that are in this state (which is roughly the number of PVs I've dropped the finalizers for).

#### Additional Notes
This is a test cluster we are using to migrate our legacy application to. Thus, there are a lot of PVs being created and deleted as we test various apps.

**Comment by asauber** [comment]
Thank you for reporting this. Clearly a serious issue if only because it's generating so much log noise.

Would you be able to paste the container tag for the CSI which is being used?

**Comment by gbates101** [comment]
@asauber Sure, its quay.io/k8scsi/csi-provisioner:v1.0.0

**Comment by asauber** [comment]
@gbates101 I meant the version of the Linode CSI driver container for example

```
linode/linode-blockstorage-csi-driver:v0.1.1
```

You can find these with 

```
k describe pod -A -l app=csi-linode-controller
k describe pod -A -l app=csi-linode-node
```

**Comment by gbates101** [comment]
@asauber Ah, sorry. Here it is:
```
linode/linode-blockstorage-csi-driver:v0.0.3
```

**Comment by asauber** [comment]
Hi @gbates101 can you try updating to the latest release of the driver?

You can do that as follows.

`k edit statefulset -n kube-system csi-linode-controller`
`k edit daemonset -n kube-system csi-linode-node`

Change both of the the relevant image names to the following.

`image: linode/linode-blockstorage-csi-driver:v0.1.3`
