### ISSUE TITLE
ERROR RESTY Failed to set up metadata service

### ISSUE THREAD

**Issue by huanshaolin** [linode/linode-blockstorage-csi-driver#79]
Hi, i have a issue setup *csi-linode-controller*, i received error below:
2022/01/05 11:13:48.270204 ERROR RESTY Get "https://api.linode.com/v4/linode/instances/31431201": net/http: invalid header field value "Bearer ${TOKEN}\n" for key Authorization, Attempt 1                                                                                                                                                                           F0105 11:13:48.270235       1 main.go:72] Failed to set up metadata service: [002] Get "https://api.linode.com/v4/linode/instances/31431201": net/http: invalid header field value "Bearer ${TOKEN}\n" for key Authorization       .
Please help me, thanks.

**Comment by Charliekenney23** [comment]
Hi @huanshaolin!

Are you deploying this yourself, or are you getting this on an LKE Cluster?

**Comment by huanshaolin** [comment]
> Hi @huanshaolin!
> 
> Are you deploying this yourself, or are you getting this on an LKE Cluster?
> 
> [This](https://github.com/golang/go/blob/2c58bb2e428c1f587dc30817bc211570f6fd4793/src/net/http/transport.go#L528) is the source of your error. If you deployed this yourself, perhaps you meant to expand the environment variable `TOKEN`, but instead, `"$TOKEN"` is being treated as your API Token. You'd want to look [here](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) to bind a secret to an environment variable.
> 
> If this is an error on an LKE Cluster, please reach out to support so we can take a look at your cluster.

Thanks for your answer.
I get this on LKE cluster. I will try it

**Comment by valerauko** [comment]
I use the yaml provided in this repo to install the driver. 0.3.0 has no problems, but upgrading 0.5.0 causes a similar `Failed to set up metadata service` error. I did not change anything about the contents of the yaml. Any idea what could be causing this?

**Comment by schinmai-akamai** [comment]
@valerauko - Nothing has changed in how the token is read between those two releases. Can you try using the helm chart? - It sets up the secrets correctly, and is the recommended way to use the driver now. Please re-open the issue if you have problems with the helm chart
